### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by romain-michalec** [romain-michalec/stabs-2021-template#1]
- [x] Investigate alternative implementation of front matter
- [x] Check correct usage of `geometry` and `times` packages
- [x] Improve header and footnotes
- [x] Check trailing newlines in source files
- [x] Page numbers in header in non-final mode
- [x] Improve appendices
- [x] Add BibLaTeX support
- [x] Add package for redacting names
- [x] Add missing sections in `template.tex`
- [x] Investigate need for the `enumerate` package
- [x] Automatically add dot after paragraph titles
- [x] Fix spacing before `\paragraph`
